# Generated by Django 5.2.4 on 2025-07-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeratelog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='exchangeratelog',
            unique_together=set(),
        ),
    ]
